spring.application.name=retry-replay-framework
# Server
server.port=8080

# H2 Database
spring.datasource.url=jdbc:h2:mem:retrydb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update

# Quartz Scheduler
spring.quartz.job-store-type=memory
spring.quartz.properties.org.quartz.threadPool.threadCount=5
spring.quartz.startup-delay=5s
logging.level.org.quartz=DEBUG


# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=retrytest15@gmail.com
spring.mail.password=tfsipoizpgvghiqg
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.notification.recipient=ramigayam1001@gmail.com

# Logging
logging.level.org.springframework=INFO
logging.level.com.example.retry=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%X{correlationId}] %-5level %logger{36} - %msg%n
